<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="congaAnnotation" nsURI="congaAnnotation" nsPrefix="congaAnnotation">
  <eClassifiers xsi:type="ecore:EClass" name="Annotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticSimilarities" upperBound="-1"
        eType="#//SemanticSimilarity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tpAvgSims" upperBound="-1"
        eType="#//TPAvg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tpIntentAvgSims" upperBound="-1"
        eType="#//TPIntentAvgSim" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intentIntentValues" upperBound="-1"
        eType="#//IntentIntentValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intentValues" upperBound="-1"
        eType="#//IntentValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticSimilarity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trainingPhrase1" lowerBound="1"
        eType="ecore:EClass BotGenerator.ecore#//TrainingPhrase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trainingPhrase2" lowerBound="1"
        eType="ecore:EClass BotGenerator.ecore#//TrainingPhrase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="similarity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TPAvg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trainingPhrase" lowerBound="1"
        eType="ecore:EClass BotGenerator.ecore#//TrainingPhrase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="avg" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="min" lowerBound="1" eType="ecore:EClass BotGenerator.ecore#//TrainingPhrase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max" lowerBound="1" eType="ecore:EClass BotGenerator.ecore#//TrainingPhrase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TPIntentAvgSim">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trainingPhrase" lowerBound="1"
        eType="ecore:EClass BotGenerator.ecore#//TrainingPhrase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intent" lowerBound="1"
        eType="ecore:EClass BotGenerator.ecore#//Intent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="avg" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="min" lowerBound="1" eType="ecore:EClass BotGenerator.ecore#//TrainingPhrase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max" lowerBound="1" eType="ecore:EClass BotGenerator.ecore#//TrainingPhrase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntentValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="intent" lowerBound="1"
        eType="ecore:EClass BotGenerator.ecore#//Intent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="min1" lowerBound="1" eType="ecore:EClass BotGenerator.ecore#//TrainingPhrase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max1" lowerBound="1" eType="ecore:EClass BotGenerator.ecore#//TrainingPhrase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min1Value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max1Value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="min2" lowerBound="1" eType="ecore:EClass BotGenerator.ecore#//TrainingPhrase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max2" lowerBound="1" eType="ecore:EClass BotGenerator.ecore#//TrainingPhrase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min2Value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max2Value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntentIntentValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="intent1" lowerBound="1"
        eType="ecore:EClass BotGenerator.ecore#//Intent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intent2" lowerBound="1"
        eType="ecore:EClass BotGenerator.ecore#//Intent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="min1" lowerBound="1" eType="ecore:EClass BotGenerator.ecore#//TrainingPhrase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max1" lowerBound="1" eType="ecore:EClass BotGenerator.ecore#//TrainingPhrase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min1Value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max1Value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="min2" lowerBound="1" eType="ecore:EClass BotGenerator.ecore#//TrainingPhrase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max2" lowerBound="1" eType="ecore:EClass BotGenerator.ecore#//TrainingPhrase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min2Value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max2Value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
</ecore:EPackage>
